[package]
name = "cargo-commit"
version = "0.1.0"
authors = ["Alic Szecsei <aszecsei@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.7"
dialoguer = "0.4"
serde = {version = "1.0", features = ["derive"]}
strum = "0.15"
strum_macros = "0.15"
textwrap = "0.11"